import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[shell]
program = "/opt/homebrew/bin/fish"

[font]
normal = { family = "CommitMono Nerd Font", style = "Regular" }
size = 16

[keyboard]
bindings = [
  # Prevent new tabs from being created
  { key = "T", mods = "Command", action = "ReceiveChar" },
  # Cmd + arrows jump to start/end
  { key = "Left", mods = "Command", chars = "\u001bOH" },
  { key = "Right", mods = "Command", chars = "\u001bOF" },
  # Cmd + backspace deletes to start of line
  { key = "Back", mods = "Command", chars = "\u0015" },
]

[env]
TERM = "xterm-256color"
